In [2]:
# import necessary libraries
from resemblyzer import preprocess_wav, VoiceEncoder
from  pathlib import Path 
from tqdm import tqdm 
import numpy as np 
from IPython.display import Audio 
from itertools import groupby
import heapq

from os import listdir
from os.path import isfile, join, basename
from  pathlib import Path 
import numpy as np

In [4]:
dir_path = "dataset/uvr-mdx-net-split/vocals_chunks"
audio_files = [join(dir_path, f) for f in listdir(dir_path) if "mp3" in f and isfile(join(dir_path, f))]

resemblyzer_vectors = []
failed_files = []
for f in audio_files:
    try:
        print(f)
        wav = preprocess_wav(f)
        print(wav)

        encoder = VoiceEncoder()
        embed = encoder.embed_utterance(wav)
        np.set_printoptions(precision=3, suppress=True)
        resemblyzer_vectors.append(embed)
    except:
        failed_files.append(f)

resemblyzer_vectors = np.array(resemblyzer_vectors)
print(resemblyzer_vectors.shape)
print("Failed Files: ")
print(failed_files)

dataset/uvr-mdx-net-split/vocals_chunks/004  Avicii - Wake Me Up_(Vocals)_UVR-MDX-NET-Inst_HQ_3-chunk-15.mp3
[-0.002 -0.004  0.001 ...  0.066  0.033  0.057]
Loaded the voice encoder model on cpu in 0.03 seconds.
dataset/uvr-mdx-net-split/vocals_chunks/030  Naughty Boy - La La La (Feat. Sam Smith)_(Vocals)_UVR-MDX-NET-Inst_HQ_3-chunk-17.mp3
[-0.024  0.017  0.118 ...  0.051 -0.011  0.01 ]
Loaded the voice encoder model on cpu in 0.02 seconds.
dataset/uvr-mdx-net-split/vocals_chunks/018  Luke Bryan - Play It Again_(Vocals)_UVR-MDX-NET-Inst_HQ_3-chunk-6.mp3
[-0.276 -0.536 -0.481 ...  0.006  0.027  0.056]
Loaded the voice encoder model on cpu in 0.01 seconds.
dataset/uvr-mdx-net-split/vocals_chunks/033  Clarity - Zedd ft Foxes_(Vocals)_UVR-MDX-NET-Inst_HQ_3-chunk-14.mp3
[ 0.118  0.175  0.109 ...  0.011  0.034 -0.03 ]
Loaded the voice encoder model on cpu in 0.00 seconds.
dataset/uvr-mdx-net-split/vocals_chunks/100  John Legend - All Of Me_(Vocals)_UVR-MDX-NET-Inst_HQ_3-chunk-10.mp3
[ 0.002 

/opt/homebrew/anaconda3/envs/cs7643-finalproject/lib/python3.9/site-packages/resemblyzer/audio.py:27: UserWarning: PySoundFile failed. Trying audioread instead.
  wav, source_sr = librosa.load(str(fpath_or_wav), sr=None)
/opt/homebrew/anaconda3/envs/cs7643-finalproject/lib/python3.9/site-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)


dataset/uvr-mdx-net-split/vocals_chunks/005  Drake - Hold On, We're Going Home Ft. Majid Jordan_(Vocals)_UVR-MDX-NET-Inst_HQ_3-chunk-10.mp3
[-0.137 -0.161  0.021 ... -0.011 -0.025 -0.021]
Loaded the voice encoder model on cpu in 0.00 seconds.
dataset/uvr-mdx-net-split/vocals_chunks/036  Pitbull - Wild Wild Love (Feat. G.R.L.)_(Vocals)_UVR-MDX-NET-Inst_HQ_3-chunk-11.mp3
[ 0.049  0.063  0.042 ...  0.073  0.038 -0.038]
Loaded the voice encoder model on cpu in 0.00 seconds.
dataset/uvr-mdx-net-split/vocals_chunks/039  Sage the Gemini ft Iamsu - Gas Pedal_(Vocals)_UVR-MDX-NET-Inst_HQ_3-chunk-7.mp3
[ 0.003  0.004  0.004 ... -0.031 -0.068 -0.018]
Loaded the voice encoder model on cpu in 0.00 seconds.
dataset/uvr-mdx-net-split/vocals_chunks/017  Luke Bryan - Thats My Kind of Night_(Vocals)_UVR-MDX-NET-Inst_HQ_3-chunk-6.mp3
[-0.005 -0.001 -0.001 ... -0.041 -0.006  0.013]
Loaded the voice encoder model on cpu in 0.00 seconds.
dataset/uvr-mdx-net-split/vocals_chunks/058  Keith Urban - We Were Us 

In [5]:
print(resemblyzer_vectors)

[[0.    0.    0.01  ... 0.053 0.057 0.007]
 [0.    0.012 0.    ... 0.014 0.    0.013]
 [0.    0.007 0.151 ... 0.065 0.026 0.   ]
 ...
 [0.    0.033 0.015 ... 0.035 0.    0.   ]
 [0.    0.001 0.    ... 0.061 0.05  0.025]
 [0.    0.    0.006 ... 0.003 0.116 0.035]]


In [6]:
file_path = "resemblyzer_vectors.npy"
np.save(file_path, resemblyzer_vectors)

In [7]:
resemblyzer_vectors = np.load(file_path)
print(resemblyzer_vectors.shape)

(2199, 256)
