In [2]:
# import necessary libraries
from resemblyzer import preprocess_wav, VoiceEncoder
from  pathlib import Path 
from tqdm import tqdm 
import numpy as np 
from IPython.display import Audio 
from itertools import groupby
import heapq
import torchaudio as ta
from os import listdir
import os
from os.path import isfile, join, basename
from  pathlib import Path 
import numpy as np
import torch

In [3]:
dir_path = "C:/Users/baseb/.cache/huggingface/datasets/downloads/extracted"
audio_files = [join(dir_path, f) for f in listdir(dir_path) if "mp3" in f and isfile(join(dir_path, f))]

resemblyzer_vectors = []

failed_files = []
pctCounter = 1
for f in audio_files:
    os.system('cls')
    print(f'{pctCounter/len(audio_files)*100}% complete')
    pctCounter+=1
    try:
        
        #print(vocals[0].shape)
        
        #print(mono.shape)

        #print(f)
        wav = preprocess_wav(f)
        print(wav)

        #Get style encoding
        encoder = VoiceEncoder()
        embed = encoder.embed_utterance(wav)
        np.set_printoptions(precision=3, suppress=True)

        #Get Spectrogram
       

        #Add spec and style embedding to appropriate arrays
        resemblyzer_vectors.append(embed)
        
    except:
        print('failed :(')
        failed_files.append(f)

resemblyzer_vectors = np.array(resemblyzer_vectors)

print(resemblyzer_vectors.shape)
print("Number of Failed Files: ")
print(len(failed_files))

0.03729951510630362% complete
[ 0.14205933  0.20620728  0.2715149  ... -0.04165649 -0.0531311
 -0.07064819]
Loaded the voice encoder model on cpu in 0.06 seconds.


c:\Users\baseb\anaconda3\envs\cs7643-finalproject\lib\site-packages\resemblyzer\voice_encoder.py:43: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(we

0.07459903021260723% complete
[-0.015  0.053 -0.011 ... -0.022  0.009 -0.03 ]
Loaded the voice encoder model on cpu in 0.02 seconds.
0.11189854531891084% complete
[-0.063  0.003  0.049 ...  0.007  0.001 -0.003]
Loaded the voice encoder model on cpu in 0.01 seconds.


c:\Users\baseb\anaconda3\envs\cs7643-finalproject\lib\site-packages\resemblyzer\voice_encoder.py:43: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(we

0.14919806042521447% complete
[-0.007 -0.01  -0.012 ... -0.016 -0.014 -0.014]
Loaded the voice encoder model on cpu in 0.01 seconds.
0.18649757553151808% complete
[-0.005  0.014  0.033 ...  0.045  0.072  0.096]
Loaded the voice encoder model on cpu in 0.01 seconds.
0.2237970906378217% complete
[-0.02  -0.025 -0.029 ...  0.001 -0.003 -0.006]
Loaded the voice encoder model on cpu in 0.01 seconds.
0.26109660574412535% complete
[-0.005 -0.008 -0.015 ...  0.197  0.165  0.133]
Loaded the voice encoder model on cpu in 0.01 seconds.
0.29839612085042894% complete
[-0.187 -0.217 -0.236 ...  0.012  0.005 -0.001]
Loaded the voice encoder model on cpu in 0.01 seconds.
0.3356956359567326% complete
[-0.059 -0.111 -0.159 ...  0.006  0.018  0.017]
Loaded the voice encoder model on cpu in 0.01 seconds.
0.37299515106303616% complete
[ 0.01   0.004 -0.006 ... -0.012 -0.009 -0.006]
Loaded the voice encoder model on cpu in 0.01 seconds.
0.41029466616933974% complete
[ 0.021 -0.008 -0.033 ... -0.132 -0.135 -

In [4]:
print(resemblyzer_vectors)

[[0.    0.016 0.01  ... 0.    0.146 0.   ]
 [0.    0.022 0.009 ... 0.    0.143 0.   ]
 [0.018 0.006 0.    ... 0.    0.126 0.   ]
 ...
 [0.001 0.001 0.006 ... 0.012 0.183 0.007]
 [0.    0.021 0.    ... 0.02  0.145 0.   ]
 [0.    0.011 0.    ... 0.025 0.136 0.   ]]


In [5]:
file_path = "speech_resemblyzer_vectors.npy"

np.save(file_path, resemblyzer_vectors)


In [6]:
resemblyzer_vectors = np.load(file_path)

print(resemblyzer_vectors.shape)




(2681, 256)
